---
- name:
  hosts: all
  become: yes
  tasks:
    - name: Install latest Maria-db when host RAM greater than 900Mb
      yum:
        name: mariadb-server
        state: latest
        when: ansible\memetotal\mb > 900
