---
- hosts: centos7
  become: yes
  tasks:
    - name: Create users from hash
      user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: 'jane', groups: 'wheel' }
        - { name: 'joe', groups: 'cdrom' }
        - { name: 'mike', groups: 'root' }
